tierbreakers/config/routes.rb
Rails.application.routes.draw do
  resources :teams_tournaments

  resources :players_round_robins

  resources :round_robins

  resources :games_players

  resources :events_games

  resources :brackets

  resources :events_teams

  resources :team_players

  resources :teams

  resources :players

  resources :game_characters

  resources :games

  resources :events

  resources :venues

  resources :tournaments

end

tierbreakers/app/models/bracket.rb
class Bracket < ActiveRecord::Base
  belongs_to :player, :class_name => "Player1", :foreign_key => "player1_id"
  belongs_to :player, :class_name => "Player2", :foreign_key => "player2_id"
  belongs_to :player, :class_name => "Winner", :foreign_key => "winner_id"
  belongs_to :event
  belongs_to :player, :class_name => "Match1", :foreign_key => "match1_id"
  belongs_to :player, :class_name => "Match2", :foreign_key => "match2_id"
  belongs_to :player, :class_name => "Match3", :foreign_key => "match3_id"
  belongs_to :player, :class_name => "Match4", :foreign_key => "match4_id"
  belongs_to :player, :class_name => "Match5", :foreign_key => "match5_id"
end

tierbreakers/app/models/event.rb
class Event < ActiveRecord::Base
   belongs_to :tournament
   belongs_to :venue
   accepts_nested_attributes_for :venue
   accepts_nested_attributes_for :tournament 
   has_and_belongs_to_many :teams 
   has_and_belongs_to_many :games 
   has_and_belongs_to_many :players 
   has_many :round_robins, dependent: :destroy 
end

tierbreakers/app/models/events_game.rb
class EventsGame < ActiveRecord::Base
  belongs_to :game
  belongs_to :event
  accepts_nested_attributes_for :game
  accepts_nested_attributes_for :event 
end

tierbreakers/app/models/events_team.rb
class EventsTeam < ActiveRecord::Base
  belongs_to :team
  belongs_to :event
  accepts_nested_attributes_for :team
  accepts_nested_attributes_for :event 
end

tierbreakers/app/models/game.rb
class Game < ActiveRecord::Base
end

tierbreakers/app/models/game_character.rb
class GameCharacter < ActiveRecord::Base
  belongs_to :game
end

tierbreakers/app/models/games_player.rb
class GamesPlayer < ActiveRecord::Base
  belongs_to :game
  belongs_to :player
  belongs_to :game_character
  belongs_to :game_character
  belongs_to :game_character
end

tierbreakers/app/models/player.rb
class Player < ActiveRecord::Base
end

tierbreakers/app/models/round_robin.rb
class RoundRobin < ActiveRecord::Base
  belongs_to :team
  belongs_to :team
  belongs_to :player
  belongs_to :event
end

tierbreakers/app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :player
end

tierbreakers/app/models/team_player.rb
class TeamPlayer < ActiveRecord::Base
  belongs_to :team
  belongs_to :player
end

tierbreakers/app/models/teams_tournament.rb
class TeamsTournament < ActiveRecord::Base
  belongs_to :team
  belongs_to :tournament
end

tierbreakers/app/models/tournament.rb
class Tournament < ActiveRecord::Base
end

tierbreakers/app/models/venue.rb
class Venue < ActiveRecord::Base
  
end

tierbreakers/app/controllers/brackets_controller.rb
class BracketsController < ApplicationController
  before_action :set_bracket, only: [:show, :edit, :update, :destroy]

  # GET /brackets
  # GET /brackets.json
  def index
    @brackets = Bracket.all
  end

  # GET /brackets/1
  # GET /brackets/1.json
  def show
  end

  # GET /brackets/new
  def new
    @bracket = Bracket.new
  end

  # GET /brackets/1/edit
  def edit
  end

  # POST /brackets
  # POST /brackets.json
  def create
    @bracket = Bracket.new(bracket_params)

    respond_to do |format|
      if @bracket.save
        format.html { redirect_to @bracket, notice: 'Bracket was successfully created.' }
        format.json { render :show, status: :created, location: @bracket }
      else
        format.html { render :new }
        format.json { render json: @bracket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brackets/1
  # PATCH/PUT /brackets/1.json
  def update
    respond_to do |format|
      if @bracket.update(bracket_params)
        format.html { redirect_to @bracket, notice: 'Bracket was successfully updated.' }
        format.json { render :show, status: :ok, location: @bracket }
      else
        format.html { render :edit }
        format.json { render json: @bracket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brackets/1
  # DELETE /brackets/1.json
  def destroy
    @bracket.destroy
    respond_to do |format|
      format.html { redirect_to brackets_url, notice: 'Bracket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bracket
      @bracket = Bracket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bracket_params
      params.require(:bracket).permit(:player_id, :player_id, :bracket_round, :player_id, :event_id, :type, :player_id, :player_id, :player_id, :player_id, :player_id)
    end
end

tierbreakers/app/helpers/application_helper.rb
module ApplicationHelper
end

tierbreakers/app/helpers/brackets_helper.rb
module BracketsHelper
end

tierbreakers/app/helpers/events_helper.rb
module EventsHelper
end

tierbreakers/app/helpers/games_helper.rb
module GamesHelper
end

tierbreakers/app/helpers/players_helper.rb
module PlayersHelper
end

tierbreakers/app/helpers/teams_helper.rb
module TeamsHelper
end

tierbreakers/app/helpers/tournaments_helper.rb
module TournamentsHelper
end

tierbreakers/app/helpers/venues_helper.rb
module VenuesHelper
end

tierbreakers/app/views/brackets/_form.html.erb
<%= form_for(@bracket) do |f| %>
  <% if @bracket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bracket.errors.count, "error") %> prohibited this bracket from being saved:</h2>

      <ul>
      <% @bracket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :player_id %><br>
    <%= f.text_field :player_id %>
  </div>
  <div class="field">
    <%= f.label :player_id %><br>
    <%= f.text_field :player_id %>
  </div>
  <div class="field">
    <%= f.label :bracket_round %><br>
    <%= f.number_field :bracket_round %>
  </div>
  <div class="field">
    <%= f.label :player_id %><br>
    <%= f.text_field :player_id %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.text_field :event_id %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :player_id %><br>
    <%= f.text_field :player_id %>
  </div>
  <div class="field">
    <%= f.label :player_id %><br>
    <%= f.text_field :player_id %>
  </div>
  <div class="field">
    <%= f.label :player_id %><br>
    <%= f.text_field :player_id %>
  </div>
  <div class="field">
    <%= f.label :player_id %><br>
    <%= f.text_field :player_id %>
  </div>
  <div class="field">
    <%= f.label :player_id %><br>
    <%= f.text_field :player_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

tierbreakers/app/views/brackets/edit.html.erb
<h1>Editing bracket</h1>

<%= render 'form' %>

<%= link_to 'Show', @bracket %> |
<%= link_to 'Back', brackets_path %>

tierbreakers/app/views/brackets/index.html.erb
<h1>Listing brackets</h1>

<table>
  <thead>
    <tr>
      <th>Player</th>
      <th>Player</th>
      <th>Bracket round</th>
      <th>Player</th>
      <th>Event</th>
      <th>Type</th>
      <th>Player</th>
      <th>Player</th>
      <th>Player</th>
      <th>Player</th>
      <th>Player</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brackets.each do |bracket| %>
      <tr>
        <td><%= bracket.player %></td>
        <td><%= bracket.player %></td>
        <td><%= bracket.bracket_round %></td>
        <td><%= bracket.player %></td>
        <td><%= bracket.event %></td>
        <td><%= bracket.type %></td>
        <td><%= bracket.player %></td>
        <td><%= bracket.player %></td>
        <td><%= bracket.player %></td>
        <td><%= bracket.player %></td>
        <td><%= bracket.player %></td>
        <td><%= link_to 'Show', bracket %></td>
        <td><%= link_to 'Edit', edit_bracket_path(bracket) %></td>
        <td><%= link_to 'Destroy', bracket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bracket', new_bracket_path %>

tierbreakers/app/views/brackets/new.html.erb
<h1>New bracket</h1>

<%= render 'form' %>

<%= link_to 'Back', brackets_path %>

tierbreakers/app/views/brackets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Player:</strong>
  <%= @bracket.player %>
</p>

<p>
  <strong>Player:</strong>
  <%= @bracket.player %>
</p>

<p>
  <strong>Bracket round:</strong>
  <%= @bracket.bracket_round %>
</p>

<p>
  <strong>Player:</strong>
  <%= @bracket.player %>
</p>

<p>
  <strong>Event:</strong>
  <%= @bracket.event %>
</p>

<p>
  <strong>Type:</strong>
  <%= @bracket.type %>
</p>

<p>
  <strong>Player:</strong>
  <%= @bracket.player %>
</p>

<p>
  <strong>Player:</strong>
  <%= @bracket.player %>
</p>

<p>
  <strong>Player:</strong>
  <%= @bracket.player %>
</p>

<p>
  <strong>Player:</strong>
  <%= @bracket.player %>
</p>

<p>
  <strong>Player:</strong>
  <%= @bracket.player %>
</p>

<%= link_to 'Edit', edit_bracket_path(@bracket) %> |
<%= link_to 'Back', brackets_path %>