tierbreakers/config/routes.rb
Rails.application.routes.draw do
  resources :teams_tournaments

  resources :players_round_robins

  resources :round_robins

  resources :games_players

  resources :events_games

  resources :brackets

  resources :events_teams

  resources :team_players

  resources :teams

  resources :players

  resources :game_characters

  resources :games

  resources :events

  resources :venues

  resources :tournaments

end

tierbreakers/app/models/bracket.rb
class Bracket < ActiveRecord::Base
  belongs_to :player, :class_name => "Player1", :foreign_key => "player1_id"
  belongs_to :player, :class_name => "Player2", :foreign_key => "player2_id"
  belongs_to :player, :class_name => "Winner", :foreign_key => "winner_id"
  belongs_to :event
  belongs_to :player, :class_name => "Match1", :foreign_key => "match1_id"
  belongs_to :player, :class_name => "Match2", :foreign_key => "match2_id"
  belongs_to :player, :class_name => "Match3", :foreign_key => "match3_id"
  belongs_to :player, :class_name => "Match4", :foreign_key => "match4_id"
  belongs_to :player, :class_name => "Match5", :foreign_key => "match5_id"
end

tierbreakers/app/models/event.rb
class Event < ActiveRecord::Base
   belongs_to :tournament
   belongs_to :venue
   accepts_nested_attributes_for :venue
   accepts_nested_attributes_for :tournament 
   has_and_belongs_to_many :teams 
   has_and_belongs_to_many :games 
   has_and_belongs_to_many :players 
   has_many :round_robins, dependent: :destroy 
end

tierbreakers/app/models/events_game.rb
class EventsGame < ActiveRecord::Base
  belongs_to :game
  belongs_to :event
  accepts_nested_attributes_for :game
  accepts_nested_attributes_for :event 
end

tierbreakers/app/models/events_team.rb
class EventsTeam < ActiveRecord::Base
  belongs_to :team
  belongs_to :event
  accepts_nested_attributes_for :team
  accepts_nested_attributes_for :event 
end

tierbreakers/app/models/game.rb
class Game < ActiveRecord::Base
end

tierbreakers/app/models/game_character.rb
class GameCharacter < ActiveRecord::Base
  belongs_to :game
end

tierbreakers/app/models/games_player.rb
class GamesPlayer < ActiveRecord::Base
  belongs_to :game
  belongs_to :player
  belongs_to :game_character
  belongs_to :game_character
  belongs_to :game_character
end

tierbreakers/app/models/player.rb
class Player < ActiveRecord::Base
end

tierbreakers/app/models/round_robin.rb
class RoundRobin < ActiveRecord::Base
  belongs_to :team
  belongs_to :team
  belongs_to :player
  belongs_to :event
end

tierbreakers/app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :player
end

tierbreakers/app/models/team_player.rb
class TeamPlayer < ActiveRecord::Base
  belongs_to :team
  belongs_to :player
end

tierbreakers/app/models/teams_tournament.rb
class TeamsTournament < ActiveRecord::Base
  belongs_to :team
  belongs_to :tournament
end

tierbreakers/app/models/tournament.rb
class Tournament < ActiveRecord::Base
end

tierbreakers/app/models/venue.rb
class Venue < ActiveRecord::Base
  
end

tierbreakers/app/controllers/events_controller.rb
require 'pp'
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:event_name, :event_date, :venue_id, :venue_name, :event_description, :event_image, :tournament_id, :tournament_name)
    end
end

tierbreakers/app/helpers/application_helper.rb
module ApplicationHelper
end

tierbreakers/app/helpers/brackets_helper.rb
module BracketsHelper
end

tierbreakers/app/helpers/events_helper.rb
module EventsHelper
end

tierbreakers/app/helpers/games_helper.rb
module GamesHelper
end

tierbreakers/app/helpers/players_helper.rb
module PlayersHelper
end

tierbreakers/app/helpers/teams_helper.rb
module TeamsHelper
end

tierbreakers/app/helpers/tournaments_helper.rb
module TournamentsHelper
end

tierbreakers/app/helpers/venues_helper.rb
module VenuesHelper
end

tierbreakers/app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_name %><br>
    <%= f.text_field :event_name %>
  </div>
  <div class="field">
    <%= f.label :event_date %><br>
    <%= f.datetime_select :event_date %>
  </div>
  <div class="field">
    <%= f.label :venue_id %><br>
    <%= f.select(:venue_id) do %>
	<% 
	  Venue.all.each do |venue| -%>
	 	<option value="<%= venue.id %>"><%= venue.venue_name %></option>
	  <% end %>
	<% end %>
  </div>
  <div class="field">
    <%= f.label :event_description %><br>
    <%= f.text_field :event_description %>
  </div>
  <div class="field">
    <%= f.label :event_image %><br>
    <%= f.text_field :event_image %>
  </div>
  <div class="field"> 
    <%= f.label :tournament_id %><br>
    <%= f.select(:tournament_id) do %>
	<% 
	  Tournament.all.each do |tourney| -%>
	 	<option value="<%= tourney.id %>"><%= tourney.tournament_name %></option>
	  <% end %>
	<% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

tierbreakers/app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

tierbreakers/app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Event name</th>
      <th>Event date</th>
      <th>Venue</th>
      <th>Event description</th>
      <th>Event image</th>
      <th>Tournament</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.event_name %></td>
        <td><%= event.event_date %></td>
        <td><%= event.venue_id %></td>
        <td><%= event.event_description %></td>
        <td><%= event.event_image %></td>
        <td><% the_tournament = Tournament.find(event.tournament_id) %>
  		<%= the_tournament.tournament_name %>
			</td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

tierbreakers/app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

tierbreakers/app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event name:</strong>
  <%= @event.event_name %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @event.event_date %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @event.venue_id %>
  <% the_venue = Venue.find(@event.venue_id) %>
  <%= the_venue.venue_name %>
</p>

<p>
  <strong>Event description:</strong>
  <%= @event.event_description %>
</p>

<p>
  <strong>Event image:</strong>
  <%= @event.event_image %>
</p>

<p>
  <strong>Tournament:</strong>
  <% the_tournament = Tournament.find(@event.tournament_id) %>
  <%= the_tournament.tournament_name %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>