tierbreakers/config/routes.rb
Rails.application.routes.draw do
  resources :teams_tournaments

  resources :players_round_robins

  resources :round_robins

  resources :games_players

  resources :events_games

  resources :brackets

  resources :events_teams

  resources :team_players

  resources :teams

  resources :players

  resources :game_characters

  resources :games

  resources :events

  resources :venues

  resources :tournaments

end

tierbreakers/app/models/bracket.rb
class Bracket < ActiveRecord::Base
  belongs_to :player, :class_name => "Player1", :foreign_key => "player1_id"
  belongs_to :player, :class_name => "Player2", :foreign_key => "player2_id"
  belongs_to :player, :class_name => "Winner", :foreign_key => "winner_id"
  belongs_to :event
  belongs_to :player, :class_name => "Match1", :foreign_key => "match1_id"
  belongs_to :player, :class_name => "Match2", :foreign_key => "match2_id"
  belongs_to :player, :class_name => "Match3", :foreign_key => "match3_id"
  belongs_to :player, :class_name => "Match4", :foreign_key => "match4_id"
  belongs_to :player, :class_name => "Match5", :foreign_key => "match5_id"
end

tierbreakers/app/models/event.rb
class Event < ActiveRecord::Base
   belongs_to :tournament
   belongs_to :venue
   accepts_nested_attributes_for :venue
   accepts_nested_attributes_for :tournament 
   has_and_belongs_to_many :teams 
   has_and_belongs_to_many :games 
   has_and_belongs_to_many :players 
   has_many :round_robins, dependent: :destroy 
end

tierbreakers/app/models/events_game.rb
class EventsGame < ActiveRecord::Base
  belongs_to :game
  belongs_to :event
  accepts_nested_attributes_for :game
  accepts_nested_attributes_for :event 
end

tierbreakers/app/models/events_team.rb
class EventsTeam < ActiveRecord::Base
  belongs_to :team
  belongs_to :event
  accepts_nested_attributes_for :team
  accepts_nested_attributes_for :event 
end

tierbreakers/app/models/game.rb
class Game < ActiveRecord::Base
end

tierbreakers/app/models/game_character.rb
class GameCharacter < ActiveRecord::Base
  belongs_to :game
end

tierbreakers/app/models/games_player.rb
class GamesPlayer < ActiveRecord::Base
  belongs_to :game
  belongs_to :player
  belongs_to :game_character
  belongs_to :game_character
  belongs_to :game_character
end

tierbreakers/app/models/player.rb
class Player < ActiveRecord::Base
end

tierbreakers/app/models/players_round_robin.rb
class PlayersRoundRobin < ActiveRecord::Base
  belongs_to :player
  belongs_to :player
  belongs_to :player
  belongs_to :round_robin
  belongs_to :player
  belongs_to :player
  belongs_to :player
end

tierbreakers/app/models/round_robin.rb
class RoundRobin < ActiveRecord::Base
  belongs_to :team
  belongs_to :team
  belongs_to :player
  belongs_to :event
end

tierbreakers/app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :player
end

tierbreakers/app/models/team_player.rb
class TeamPlayer < ActiveRecord::Base
  belongs_to :team
  belongs_to :player
end

tierbreakers/app/models/teams_tournament.rb
class TeamsTournament < ActiveRecord::Base
  belongs_to :team
  belongs_to :tournament
end

tierbreakers/app/models/tournament.rb
class Tournament < ActiveRecord::Base
end

tierbreakers/app/models/venue.rb
class Venue < ActiveRecord::Base
  
end

tierbreakers/app/controllers/players_round_robins_controller.rb
class PlayersRoundRobinsController < ApplicationController
  before_action :set_players_round_robin, only: [:show, :edit, :update, :destroy]

  # GET /players_round_robins
  # GET /players_round_robins.json
  def index
    @players_round_robins = PlayersRoundRobin.all
  end

  # GET /players_round_robins/1
  # GET /players_round_robins/1.json
  def show
  end

  # GET /players_round_robins/new
  def new
    @players_round_robin = PlayersRoundRobin.new
  end

  # GET /players_round_robins/1/edit
  def edit
  end

  # POST /players_round_robins
  # POST /players_round_robins.json
  def create
    @players_round_robin = PlayersRoundRobin.new(players_round_robin_params)

    respond_to do |format|
      if @players_round_robin.save
        format.html { redirect_to @players_round_robin, notice: 'Players round robin was successfully created.' }
        format.json { render :show, status: :created, location: @players_round_robin }
      else
        format.html { render :new }
        format.json { render json: @players_round_robin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players_round_robins/1
  # PATCH/PUT /players_round_robins/1.json
  def update
    respond_to do |format|
      if @players_round_robin.update(players_round_robin_params)
        format.html { redirect_to @players_round_robin, notice: 'Players round robin was successfully updated.' }
        format.json { render :show, status: :ok, location: @players_round_robin }
      else
        format.html { render :edit }
        format.json { render json: @players_round_robin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players_round_robins/1
  # DELETE /players_round_robins/1.json
  def destroy
    @players_round_robin.destroy
    respond_to do |format|
      format.html { redirect_to players_round_robins_url, notice: 'Players round robin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_players_round_robin
      @players_round_robin = PlayersRoundRobin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def players_round_robin_params
      params.require(:players_round_robin).permit(:player_id, :player_id, :player_id, :round_robin_id, :player_id, :player_id, :player_id)
    end
end

tierbreakers/app/helpers/brackets_helper.rb
module BracketsHelper
end

tierbreakers/app/helpers/events_helper.rb
module EventsHelper
end

tierbreakers/app/helpers/games_helper.rb
module GamesHelper
end

tierbreakers/app/helpers/players_helper.rb
module PlayersHelper
end

tierbreakers/app/helpers/players_round_robins_helper.rb
module PlayersRoundRobinsHelper
end

tierbreakers/app/helpers/teams_helper.rb
module TeamsHelper
end

tierbreakers/app/helpers/venues_helper.rb
module VenuesHelper
end

tierbreakers/app/views/players_round_robins/_form.html.erb
<%= form_for(@players_round_robin) do |f| %>
  <% if @players_round_robin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@players_round_robin.errors.count, "error") %> prohibited this players_round_robin from being saved:</h2>

      <ul>
      <% @players_round_robin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :player_id %><br>
    <%= f.text_field :player_id %>
  </div>
  <div class="field">
    <%= f.label :player_id %><br>
    <%= f.text_field :player_id %>
  </div>
  <div class="field">
    <%= f.label :player_id %><br>
    <%= f.text_field :player_id %>
  </div>
  <div class="field">
    <%= f.label :round_robin_id %><br>
    <%= f.text_field :round_robin_id %>
  </div>
  <div class="field">
    <%= f.label :player_id %><br>
    <%= f.text_field :player_id %>
  </div>
  <div class="field">
    <%= f.label :player_id %><br>
    <%= f.text_field :player_id %>
  </div>
  <div class="field">
    <%= f.label :player_id %><br>
    <%= f.text_field :player_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

tierbreakers/app/views/players_round_robins/edit.html.erb
<h1>Editing players_round_robin</h1>

<%= render 'form' %>

<%= link_to 'Show', @players_round_robin %> |
<%= link_to 'Back', players_round_robins_path %>

tierbreakers/app/views/players_round_robins/index.html.erb
<h1>Listing players_round_robins</h1>

<table>
  <thead>
    <tr>
      <th>Player</th>
      <th>Player</th>
      <th>Player</th>
      <th>Round robin</th>
      <th>Player</th>
      <th>Player</th>
      <th>Player</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players_round_robins.each do |players_round_robin| %>
      <tr>
        <td><%= players_round_robin.player %></td>
        <td><%= players_round_robin.player %></td>
        <td><%= players_round_robin.player %></td>
        <td><%= players_round_robin.round_robin %></td>
        <td><%= players_round_robin.player %></td>
        <td><%= players_round_robin.player %></td>
        <td><%= players_round_robin.player %></td>
        <td><%= link_to 'Show', players_round_robin %></td>
        <td><%= link_to 'Edit', edit_players_round_robin_path(players_round_robin) %></td>
        <td><%= link_to 'Destroy', players_round_robin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Players round robin', new_players_round_robin_path %>

tierbreakers/app/views/players_round_robins/new.html.erb
<h1>New players_round_robin</h1>

<%= render 'form' %>

<%= link_to 'Back', players_round_robins_path %>

tierbreakers/app/views/players_round_robins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Player:</strong>
  <%= @players_round_robin.player %>
</p>

<p>
  <strong>Player:</strong>
  <%= @players_round_robin.player %>
</p>

<p>
  <strong>Player:</strong>
  <%= @players_round_robin.player %>
</p>

<p>
  <strong>Round robin:</strong>
  <%= @players_round_robin.round_robin %>
</p>

<p>
  <strong>Player:</strong>
  <%= @players_round_robin.player %>
</p>

<p>
  <strong>Player:</strong>
  <%= @players_round_robin.player %>
</p>

<p>
  <strong>Player:</strong>
  <%= @players_round_robin.player %>
</p>

<%= link_to 'Edit', edit_players_round_robin_path(@players_round_robin) %> |
<%= link_to 'Back', players_round_robins_path %>