tierbreakers/config/routes.rb
Rails.application.routes.draw do
  resources :teams_tournaments

  resources :players_round_robins

  resources :round_robins

  resources :games_players

  resources :events_games

  resources :brackets

  resources :events_teams

  resources :team_players

  resources :teams

  resources :players

  resources :game_characters

  resources :games

  resources :events

  resources :venues

  resources :tournaments

end

tierbreakers/app/models/bracket.rb
class Bracket < ActiveRecord::Base
  belongs_to :player, :class_name => "Player1", :foreign_key => "player1_id"
  belongs_to :player, :class_name => "Player2", :foreign_key => "player2_id"
  belongs_to :player, :class_name => "Winner", :foreign_key => "winner_id"
  belongs_to :event
  belongs_to :player, :class_name => "Match1", :foreign_key => "match1_id"
  belongs_to :player, :class_name => "Match2", :foreign_key => "match2_id"
  belongs_to :player, :class_name => "Match3", :foreign_key => "match3_id"
  belongs_to :player, :class_name => "Match4", :foreign_key => "match4_id"
  belongs_to :player, :class_name => "Match5", :foreign_key => "match5_id"
end

tierbreakers/app/models/event.rb
class Event < ActiveRecord::Base
   belongs_to :tournament
   belongs_to :venue
   accepts_nested_attributes_for :venue
   accepts_nested_attributes_for :tournament 
   has_and_belongs_to_many :teams 
   has_and_belongs_to_many :games 
   has_and_belongs_to_many :players 
   has_many :round_robins, dependent: :destroy 
end

tierbreakers/app/models/events_game.rb
class EventsGame < ActiveRecord::Base
  belongs_to :game
  belongs_to :event
  accepts_nested_attributes_for :game
  accepts_nested_attributes_for :event 
end

tierbreakers/app/models/events_team.rb
class EventsTeam < ActiveRecord::Base
  belongs_to :team
  belongs_to :event
  accepts_nested_attributes_for :team
  accepts_nested_attributes_for :event 
end

tierbreakers/app/models/game.rb
class Game < ActiveRecord::Base
end

tierbreakers/app/models/game_character.rb
class GameCharacter < ActiveRecord::Base
  belongs_to :game
end

tierbreakers/app/models/games_player.rb
class GamesPlayer < ActiveRecord::Base
  belongs_to :game
  belongs_to :player
  belongs_to :game_character
  belongs_to :game_character
  belongs_to :game_character
end

tierbreakers/app/models/player.rb
class Player < ActiveRecord::Base
end

tierbreakers/app/models/round_robin.rb
class RoundRobin < ActiveRecord::Base
  belongs_to :team
  belongs_to :team
  belongs_to :player
  belongs_to :event
end

tierbreakers/app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :player
end

tierbreakers/app/models/team_player.rb
class TeamPlayer < ActiveRecord::Base
  belongs_to :team
  belongs_to :player
end

tierbreakers/app/models/teams_tournament.rb
class TeamsTournament < ActiveRecord::Base
  belongs_to :team
  belongs_to :tournament
end

tierbreakers/app/models/tournament.rb
class Tournament < ActiveRecord::Base
end

tierbreakers/app/models/venue.rb
class Venue < ActiveRecord::Base
  
end

tierbreakers/app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, only: [:show, :edit, :update, :destroy]

  # GET /tournaments
  # GET /tournaments.json
  def index
    @tournaments = Tournament.all
  end

  # GET /tournaments/1
  # GET /tournaments/1.json
  def show
  end
  
  # GET /tournaments/new
  def new
    @tournament = Tournament.new
  end

  # GET /tournaments/1/edit
  def edit
  end

  # POST /tournaments
  # POST /tournaments.json
  def create
    @tournament = Tournament.new(tournament_params)

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to @tournament, notice: 'Tournament was successfully created.' }
        format.json { render :show, status: :created, location: @tournament }
      else
        format.html { render :new }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tournaments/1
  # PATCH/PUT /tournaments/1.json
  def update
    respond_to do |format|
      if @tournament.update(tournament_params)
        format.html { redirect_to @tournament, notice: 'Tournament was successfully updated.' }
        format.json { render :show, status: :ok, location: @tournament }
      else
        format.html { render :edit }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1
  # DELETE /tournaments/1.json
  def destroy
    @tournament.destroy
    respond_to do |format|
      format.html { redirect_to tournaments_url, notice: 'Tournament was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tournament_params
      params.require(:tournament).permit(:tournament_name, :tournament_state, :tournamentcol_city, :tournament_max_players, :tournament_start_date, :tournament_end_date, :tournament_reg_start, :tournament_reg_end, :tournament_description, :tournament_game_id, :tournament_image)
    end
end

tierbreakers/app/helpers/application_helper.rb
module ApplicationHelper
end

tierbreakers/app/helpers/brackets_helper.rb
module BracketsHelper
end

tierbreakers/app/helpers/events_helper.rb
module EventsHelper
end

tierbreakers/app/helpers/games_helper.rb
module GamesHelper
end

tierbreakers/app/helpers/players_helper.rb
module PlayersHelper
end

tierbreakers/app/helpers/teams_helper.rb
module TeamsHelper
end

tierbreakers/app/helpers/tournaments_helper.rb
module TournamentsHelper
end

tierbreakers/app/helpers/venues_helper.rb
module VenuesHelper
end

tierbreakers/app/views/tournaments/_form.html.erb
<%= form_for(@tournament) do |f| %>
  <% if @tournament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

      <ul>
      <% @tournament.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tournament_name %><br>
    <%= f.text_field :tournament_name %>
  </div>
  <div class="field">
    <%= f.label :tournament_state %><br>
    <%= f.text_field :tournament_state %>
  </div>
  <div class="field">
    <%= f.label :tournamentcol_city %><br>
    <%= f.text_field :tournamentcol_city %>
  </div>
  <div class="field">
    <%= f.label :tournament_max_players %><br>
    <%= f.number_field :tournament_max_players %>
  </div>
  <div class="field">
    <%= f.label :tournament_start_date %><br>
    <%= f.datetime_select :tournament_start_date %>
  </div>
  <div class="field">
    <%= f.label :tournament_end_date %><br>
    <%= f.datetime_select :tournament_end_date %>
  </div>
  <div class="field">
    <%= f.label :tournament_reg_start %><br>
    <%= f.datetime_select :tournament_reg_start %>
  </div>
  <div class="field">
    <%= f.label :tournament_reg_end %><br>
    <%= f.datetime_select :tournament_reg_end %>
  </div>
  <div class="field">
    <%= f.label :tournament_description %><br>
    <%= f.text_field :tournament_description %>
  </div>
  <div class="field">
    <%= f.label :tournament_game_id %><br>
    <%= f.number_field :tournament_game_id %>
  </div>
  <div class="field">
    <%= f.label :tournament_image %><br>
    <%= f.text_field :tournament_image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

tierbreakers/app/views/tournaments/edit.html.erb
<h1>Editing tournament</h1>

<%= render 'form' %>

<%= link_to 'Show', @tournament %> |
<%= link_to 'Back', tournaments_path %>

tierbreakers/app/views/tournaments/index.html.erb
<h1>Listing tournaments</h1>

<table>
  <thead>
    <tr>
      <th>Tournament name</th>
      <th>Tournament state</th>
      <th>Tournamentcol city</th>
      <th>Tournament max players</th>
      <th>Tournament start date</th>
      <th>Tournament end date</th>
      <th>Tournament reg start</th>
      <th>Tournament reg end</th>
      <th>Tournament description</th>
      <th>Tournament game</th>
      <th>Tournament image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tournaments.each do |tournament| %>
      <tr>
        <td><%= tournament.tournament_name %></td>
        <td><%= tournament.tournament_state %></td>
        <td><%= tournament.tournamentcol_city %></td>
        <td><%= tournament.tournament_max_players %></td>
        <td><%= tournament.tournament_start_date %></td>
        <td><%= tournament.tournament_end_date %></td>
        <td><%= tournament.tournament_reg_start %></td>
        <td><%= tournament.tournament_reg_end %></td>
        <td><%= tournament.tournament_description %></td>
        <td><%= tournament.tournament_game_id %></td>
        <td><%= tournament.tournament_image %></td>
        <td><%= link_to 'Show', tournament %></td>
        <td><%= link_to 'Edit', edit_tournament_path(tournament) %></td>
        <td><%= link_to 'Destroy', tournament, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tournament', new_tournament_path %>

tierbreakers/app/views/tournaments/new.html.erb
<h1>New tournament</h1>

<%= render 'form' %>

<%= link_to 'Back', tournaments_path %>

tierbreakers/app/views/tournaments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tournament name:</strong>
  <%= @tournament.tournament_name %>
</p>

<p>
  <strong>Tournament state:</strong>
  <%= @tournament.tournament_state %>
</p>

<p>
  <strong>Tournamentcol city:</strong>
  <%= @tournament.tournamentcol_city %>
</p>

<p>
  <strong>Tournament max players:</strong>
  <%= @tournament.tournament_max_players %>
</p>

<p>
  <strong>Tournament start date:</strong>
  <%= @tournament.tournament_start_date %>
</p>

<p>
  <strong>Tournament end date:</strong>
  <%= @tournament.tournament_end_date %>
</p>

<p>
  <strong>Tournament reg start:</strong>
  <%= @tournament.tournament_reg_start %>
</p>

<p>
  <strong>Tournament reg end:</strong>
  <%= @tournament.tournament_reg_end %>
</p>

<p>
  <strong>Tournament description:</strong>
  <%= @tournament.tournament_description %>
</p>

<p>
  <strong>Tournament game:</strong>
  <%= @tournament.tournament_game_id %>
</p>

<p>
  <strong>Tournament image:</strong>
  <%= @tournament.tournament_image %>
</p>

<%= link_to 'Edit', edit_tournament_path(@tournament) %> |
<%= link_to 'Back', tournaments_path %>